In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from scipy import optimize
from ipywidgets import *
from IPython.display import SVG
from sklearn import datasets

In [47]:
And = pd.DataFrame({'x1':(0,0,1,1),'x2':(0,1,0,1),'y':(0,0,0,1)})
And

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [61]:
inputs = And[['x1','x2']]
target = And['y']

# Initialize a random weight

In [62]:
w = np.random.randn(3)*1e-4

# Create an Activation function

In [63]:
g = lambda inputs, weights: np.where((np.dot(inputs,weights))>0, 1, 0)

In [64]:
inputs = np.c_[inputs, -np.ones((len(inputs),1))]
activations=g(inputs,w)

In [65]:
weights = weights- (10*np.dot(np.transpose(inputs), (activations-target)))

# Finally a training function that iterates the learning algorithm , returning the adapted weights.


In [66]:
def train(inputs,targets,weights,eta,n_iterations):
    #Add the inputs that match the bias node
    inputs = np.c_[inputs, -np.ones((len(inputs),1))]
    
    for n in range(n_iterations):
        activations = g(inputs,weights);
        weights = weights- (eta*np.dot(np.transpose(inputs), (activations-targets)))
        
    return weights

In [69]:
inputs = And[['x1','x2']]
targets = And['y']

In [70]:
w = train(inputs,targets,w,10,10)

In [71]:
w

array([10.00005885, 10.00002687, 10.00011784])

# Checking the performance

In [72]:
g(np.c_[inputs, -np.ones((len(inputs),1))],w)

array([0, 0, 0, 1])

In [73]:
def train(inputs,targets,weights,eta,n_iterations):
    #Add the inputs that match the bias node
    inputs = np.c_[inputs, -np.ones((len(inputs),1))]
    
    for n in range(n_iterations):
        activations = g(inputs,weights);
        weights = weights- (eta*np.dot(np.transpose(inputs), (activations-targets)))
        print(n,weights)
        
    return weights

In [74]:
inputs = And[['x1','x2']]
targets = And['y']

In [75]:
w = train(inputs,targets,w,5,10)

0 [10.00005885 10.00002687 10.00011784]
1 [10.00005885 10.00002687 10.00011784]
2 [10.00005885 10.00002687 10.00011784]
3 [10.00005885 10.00002687 10.00011784]
4 [10.00005885 10.00002687 10.00011784]
5 [10.00005885 10.00002687 10.00011784]
6 [10.00005885 10.00002687 10.00011784]
7 [10.00005885 10.00002687 10.00011784]
8 [10.00005885 10.00002687 10.00011784]
9 [10.00005885 10.00002687 10.00011784]


In [76]:
g(np.c_[inputs, -np.ones((len(inputs),1))],w)

array([0, 0, 0, 1])